name: Deploy documentation and API reference

on:
  # If specified, the workflow will be triggered automatically once you push to the `main` branch.
  # Replace `main` with your branch’s name
  push:
    branches: [ "main" ]
  # Specify to run a workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Gives the workflow permissions to clone the repo and create a page deployment
permissions:
  id-token: write
  pages: write

env:
  # Name of module and id separated by a slash
  INSTANCE: documentation/akkurate
  # Replace HI with the ID of the instance in capital letters
  DOC_ARTIFACT: webHelpAKKURATE2-all.zip
  # Writerside docker image version
  DOCKER_VERSION: 2.1.1479-p3869
  # Add the variable below to upload Algolia indexes
  # Replace HI with the ID of the instance in capital letters
  ALGOLIA_ARTIFACT: algolia-indexes-AKKURATE.zip

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build documentation
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.DOC_ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            ./artifacts/${{ env.DOC_ARTIFACT }}
            ./artifacts/report.json
          retention-days: 7

      - name: Upload social image
        uses: actions/upload-artifact@v3
        with:
          name: social-image
          path: ./documentation/images/social.png
          retention-days: 7

      # Add the step below to upload Algolia indexes
  #      - name: Upload algolia-indexes
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: algolia-indexes
  #          path: artifacts/${{ env.ALGOLIA_ARTIFACT }}
  #          retention-days: 7

  build-api-reference:
    name: Build API reference
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0

      - name: Build the API
        run: ./gradlew dokkaHtmlMultiModule

      - name: Upload API reference
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ./build/dokka/htmlMultiModule/
          retention-days: 7

  # Add the job below and artifacts/report.json on Upload documentation step above if you want to fail the build when documentation contains errors
  test-documentation:
    name: Test documentation
    # Requires build job results
    needs: build-documentation
    runs-on: ubuntu-latest

    steps:
      - name: Download documentation
        uses: actions/download-artifact@v1
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  deploy:
    name: Deploy everything
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Requires the build job results
    needs: [ test-documentation, build-api-reference ]
    runs-on: ubuntu-latest
    steps:
      - name: Download documentation
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Unzip documentation
        run: mkdir website && unzip -qq ${{ env.DOC_ARTIFACT }} -d website/docs

      - name: Download API reference
        uses: actions/download-artifact@v3
        with:
          name: api
          path: ./website/api/

      - name: Download social image
        uses: actions/download-artifact@v3
        with:
          name: social-image
          path: ./website/

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload Pages contents
        uses: actions/upload-pages-artifact@v1
        with:
          path: website

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
